export const SCREEN_NAME = {
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  ACTIVITY_SCREEN: 'ACTIVITY_SCREEN',
  CUSTOMER_SCREEN: 'CUSTOMER_SCREEN',
  CUSTOMER_ADD_SCREEN: 'CUSTOMER_ADD_SCREEN',
  CUSTOMER_EDIT_SCREEN: 'CUSTOMER_EDIT_SCREEN',
  CUSTOMER_DETAIL_SCREEN: 'CUSTOMER_DETAIL_SCREEN',
  NOTE_SCREEN: 'NOTE_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  TAB_NAVIGATION: 'TAB_NAVIGATION',
};

export const BOTTOM_NAV = {
  RADIUS: 20,
  HEIGHT: '9%',
  PADDING_TOP: 5,
  PADDING_BOTTOM: 5,
};

export const ACTIVITY_TYPE = {
  CONTACT: 'Lien lac',
  APPOINTMENT: 'Buoi hen',
};
